function rcCentroid = spotcentroid(inputImage, threshold)
  if ~exist('threshold', 'var')
    threshold = max(inputImage, [], 'all') / 100;
  end
  [bwblobs, blobcounts] = bwlabeljj3(inputImage > threshold);
  rcCentroid = bwblobcentroidjj(bwblobs, ...
    find(...
      sum(blobcounts(:) == (1:max(blobcounts))) ... 
      == max(sum(blobcounts(:) == (1:max(blobcounts))))...
    )...
    );
end